services:
  app:
    build:
      context: .
      dockerfile: images/dev/Dockerfile
      args:
        ENV: "DEVELOP"
    image: 4erk/app:dev
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_SESSION: "PHPSTORM"
      SWOOLE_TIMEZONE: "UTC"
    volumes:
      - ./:/var/www
    ports:
      - "80:9501"