version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: images/prod/Dockerfile
      args:
        ENV: "PRODUCTION"
        SWOOLE_TIMEZONE: "UTC"
    image: 4erk/app:latest
    volumes:
      - ./:/var/www
    ports:
      - "80:9501"